import custom from 'eslint-plugin-custom'
import functional from 'eslint-plugin-functional'
import eslintPluginImport from 'eslint-plugin-import'
import lodash from 'eslint-plugin-lodash'
import n from 'eslint-plugin-n'
import promise from 'eslint-plugin-promise'
import regexp from 'eslint-plugin-regexp'
import sonarjs from 'eslint-plugin-sonarjs'
import sortDestructureKeys from 'eslint-plugin-sort-destructure-keys'
import sortKeysFix from 'eslint-plugin-sort-keys-fix'
import typescriptSortKeys from 'eslint-plugin-typescript-sort-keys'
import unicorn from 'eslint-plugin-unicorn'
import youDontNeedLodashUnderscore from 'eslint-plugin-you-dont-need-lodash-underscore'
import eslintComments from '@eslint-community/eslint-plugin-eslint-comments'
import stylistic from '@stylistic/eslint-plugin'
import tseslint from 'typescript-eslint'
import globals from 'globals'

// https://typescript-eslint.io/packages/typescript-eslint/#config
/** @type {import('@typescript-eslint/utils').TSESLint.FlatConfig.ConfigFile} */
export default [
  {
    files: ['@typesCustom/**/*.d.ts', 'src/**/*.js', 'src/**/*.jsx', 'src/**/*.ts', 'src/**/*.tsx'],
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.node,
        Atomics: 'readonly',
        BigInt: 'readonly',
        chrome: 'readonly',
        gapi: 'readonly',
        NodeJS: 'readonly',
        JSX: 'readonly',
        SharedArrayBuffer: 'readonly',
      },
      parser: tseslint.parser,
      parserOptions: {
        project: true,
        tsconfigRootDir: import.meta.dirname,
      },
      sourceType: 'module',
    },
    linterOptions: {
      reportUnusedDisableDirectives: false,
    },
    plugins: {
      'custom': custom,
      'functional': functional,
      'import': eslintPluginImport,
      'lodash': lodash,
      'n': n,
      'promise': promise,
      'regexp': regexp,
      'sonarjs': sonarjs,
      'sort-destructure-keys': sortDestructureKeys,
      'sort-keys-fix': sortKeysFix,
      'typescript-sort-keys': typescriptSortKeys,
      'unicorn': unicorn,
      'you-dont-need-lodash-underscore': youDontNeedLodashUnderscore,
      '@eslint-community/eslint-comments': eslintComments,
      '@stylistic': stylistic,
      '@typescript-eslint': tseslint.plugin,
    },
    rules: {
      '@eslint-community/eslint-comments/disable-enable-pair': ['warn'],
      '@eslint-community/eslint-comments/no-aggregating-enable': ['warn'],
      '@eslint-community/eslint-comments/no-duplicate-disable': ['warn'],
      '@eslint-community/eslint-comments/no-restricted-disable': ['warn'],
      '@eslint-community/eslint-comments/no-unlimited-disable': ['warn'],
      '@eslint-community/eslint-comments/no-unused-enable': ['warn'],
      '@stylistic/array-bracket-spacing': ['warn', 'never'],
      '@stylistic/array-element-newline': ['warn', 'consistent'],
      '@stylistic/arrow-parens': ['warn', 'as-needed'],
      '@stylistic/arrow-spacing': ['warn'],
      '@stylistic/block-spacing': ['warn'],
      '@stylistic/brace-style': ['warn', '1tbs', { allowSingleLine: true }],
      '@stylistic/comma-dangle': ['warn', 'always-multiline'],
      '@stylistic/comma-spacing': ['warn'],
      '@stylistic/comma-style': ['warn'],
      '@stylistic/computed-property-spacing': ['warn'],
      '@stylistic/curly-newline': ['warn'],
      '@stylistic/dot-location': ['warn', 'property'],
      '@stylistic/eol-last': ['warn'],
      '@stylistic/function-call-argument-newline': ['warn', 'consistent'],
      '@stylistic/generator-star-spacing': ['warn'],
      '@stylistic/key-spacing': ['warn', { afterColon: true, beforeColon: false, mode: 'minimum' }],
      '@stylistic/keyword-spacing': ['warn'],
      '@stylistic/linebreak-style': ['warn'],
      '@stylistic/lines-between-class-members': ['warn', 'always'],
      '@stylistic/member-delimiter-style': [
        'warn',
        { multiline: { delimiter: 'none', requireLast: true }, singleline: { delimiter: 'semi', requireLast: false } },
      ],
      '@stylistic/new-parens': ['warn'],
      '@stylistic/no-extra-semi': ['warn'],
      '@stylistic/no-floating-decimal': ['warn'],
      '@stylistic/no-mixed-spaces-and-tabs': ['warn'],
      '@stylistic/no-multiple-empty-lines': ['warn', { max: 1, maxEOF: 0, maxBOF: 0 }],
      '@stylistic/no-tabs': ['warn'],
      '@stylistic/no-trailing-spaces': ['warn'],
      '@stylistic/no-whitespace-before-property': ['warn'],
      '@stylistic/nonblock-statement-body-position': ['warn'],
      '@stylistic/object-curly-newline': ['warn'],
      '@stylistic/object-curly-spacing': ['warn', 'always'],
      '@stylistic/one-var-declaration-per-line': ['warn'],
      '@stylistic/padded-blocks': ['warn', 'never'],
      '@stylistic/padding-line-between-statements': ['warn'],
      '@stylistic/quote-props': ['warn', 'consistent-as-needed'],
      '@stylistic/quotes': ['warn', 'single', { avoidEscape: true }],
      '@stylistic/rest-spread-spacing': ['warn'],
      '@stylistic/semi': ['warn', 'never', { beforeStatementContinuationChars: 'never' }],
      '@stylistic/semi-spacing': ['warn'],
      '@stylistic/semi-style': ['warn'],
      '@stylistic/space-before-blocks': ['warn'],
      '@stylistic/space-before-function-paren': ['warn', { anonymous: 'always', asyncArrow: 'always', named: 'never' }],
      '@stylistic/space-in-parens': ['warn'],
      '@stylistic/space-infix-ops': ['warn'],
      '@stylistic/space-unary-ops': ['warn'],
      '@stylistic/spaced-comment': ['warn', 'always', { block: { balanced: true } }],
      '@stylistic/switch-colon-spacing': ['warn'],
      '@stylistic/template-curly-spacing': ['warn'],
      '@stylistic/template-tag-spacing': ['warn'],
      '@stylistic/type-annotation-spacing': ['warn'],
      '@stylistic/type-generic-spacing': ['warn'],
      '@stylistic/type-named-tuple-spacing': ['warn'],
      '@stylistic/wrap-iife': ['warn'],
      '@stylistic/yield-star-spacing': ['warn'],
      '@typescript-eslint/adjacent-overload-signatures': ['warn'],
      '@typescript-eslint/array-type': ['warn', { default: 'array' }],
      '@typescript-eslint/await-thenable': ['warn'],
      '@typescript-eslint/ban-ts-comment': ['warn'],
      '@typescript-eslint/ban-tslint-comment': ['warn'],
      '@typescript-eslint/class-literal-property-style': ['warn'],
      '@typescript-eslint/class-methods-use-this': ['warn'],
      '@typescript-eslint/consistent-generic-constructors': ['warn'],
      '@typescript-eslint/consistent-indexed-object-style': ['warn'],
      '@typescript-eslint/consistent-type-assertions': ['warn'],
      '@typescript-eslint/consistent-type-definitions': ['warn'],
      '@typescript-eslint/consistent-type-exports': ['warn'],
      '@typescript-eslint/consistent-type-imports': ['warn', { prefer: 'no-type-imports' }],
      '@typescript-eslint/default-param-last': ['warn'],
      '@typescript-eslint/dot-notation': ['warn'],
      '@typescript-eslint/explicit-member-accessibility': ['warn'],
      '@typescript-eslint/init-declarations': ['warn'],
      '@typescript-eslint/member-ordering': [
        'warn',
        {
          classes: {
            memberTypes: [
              'signature',
              'call-signature',
              'public-static-field',
              'protected-static-field',
              'private-static-field',
              '#private-static-field',
              'public-decorated-field',
              'protected-decorated-field',
              'private-decorated-field',
              'public-instance-field',
              'protected-instance-field',
              'private-instance-field',
              '#private-instance-field',
              'public-abstract-field',
              'protected-abstract-field',
              'public-field',
              'protected-field',
              'private-field',
              '#private-field',
              'static-field',
              'instance-field',
              'abstract-field',
              'decorated-field',
              'field',
              'static-initialization',
              'public-constructor',
              'protected-constructor',
              'private-constructor',
              'constructor',
              'public-static-accessor',
              'protected-static-accessor',
              'private-static-accessor',
              '#private-static-accessor',
              'public-decorated-accessor',
              'protected-decorated-accessor',
              'private-decorated-accessor',
              'public-instance-accessor',
              'protected-instance-accessor',
              'private-instance-accessor',
              '#private-instance-accessor',
              'public-abstract-accessor',
              'protected-abstract-accessor',
              'public-accessor',
              'protected-accessor',
              'private-accessor',
              '#private-accessor',
              'static-accessor',
              'instance-accessor',
              'abstract-accessor',
              'decorated-accessor',
              'accessor',
              'public-static-get',
              'protected-static-get',
              'private-static-get',
              '#private-static-get',
              'public-decorated-get',
              'protected-decorated-get',
              'private-decorated-get',
              'public-instance-get',
              'protected-instance-get',
              'private-instance-get',
              '#private-instance-get',
              'public-abstract-get',
              'protected-abstract-get',
              'public-get',
              'protected-get',
              'private-get',
              '#private-get',
              'static-get',
              'instance-get',
              'abstract-get',
              'decorated-get',
              'get',
              'public-static-set',
              'protected-static-set',
              'private-static-set',
              '#private-static-set',
              'public-decorated-set',
              'protected-decorated-set',
              'private-decorated-set',
              'public-instance-set',
              'protected-instance-set',
              'private-instance-set',
              '#private-instance-set',
              'public-abstract-set',
              'protected-abstract-set',
              'public-set',
              'protected-set',
              'private-set',
              '#private-set',
              'static-set',
              'instance-set',
              'abstract-set',
              'decorated-set',
              'set',
              'public-static-method',
              'protected-static-method',
              'private-static-method',
              '#private-static-method',
              'public-decorated-method',
              'protected-decorated-method',
              'private-decorated-method',
              'public-instance-method',
              'protected-instance-method',
              'private-instance-method',
              '#private-instance-method',
              'public-abstract-method',
              'protected-abstract-method',
              'public-method',
              'protected-method',
              'private-method',
              '#private-method',
              'static-method',
              'instance-method',
              'abstract-method',
              'decorated-method',
              'method',
            ],
            order: 'natural',
          },
        },
      ],
      '@typescript-eslint/method-signature-style': ['warn'],
      '@typescript-eslint/no-array-constructor': ['warn'],
      '@typescript-eslint/no-array-delete': ['warn'],
      '@typescript-eslint/no-base-to-string': ['warn'],
      '@typescript-eslint/no-confusing-non-null-assertion': ['warn'],
      '@typescript-eslint/no-confusing-void-expression': ['warn'],
      '@typescript-eslint/no-deprecated': ['warn'],
      '@typescript-eslint/no-dupe-class-members': ['warn'],
      '@typescript-eslint/no-duplicate-enum-values': ['warn'],
      '@typescript-eslint/no-duplicate-type-constituents': ['warn'],
      '@typescript-eslint/no-dynamic-delete': ['warn'],
      '@typescript-eslint/no-empty-function': ['warn'],
      '@typescript-eslint/no-empty-interface': ['warn'],
      '@typescript-eslint/no-empty-object-type': ['warn'],
      '@typescript-eslint/no-explicit-any': ['warn'],
      '@typescript-eslint/no-extra-non-null-assertion': ['warn'],
      '@typescript-eslint/no-extraneous-class': ['warn'],
      '@typescript-eslint/no-implied-eval': ['warn'],
      '@typescript-eslint/no-inferrable-types': ['warn'],
      '@typescript-eslint/no-invalid-this': ['warn'],
      '@typescript-eslint/no-invalid-void-type': ['warn'],
      '@typescript-eslint/no-loop-func': ['warn'],
      '@typescript-eslint/no-loss-of-precision': ['warn'],
      '@typescript-eslint/no-meaningless-void-operator': ['warn'],
      '@typescript-eslint/no-misused-new': ['warn'],
      '@typescript-eslint/no-misused-promises': ['warn', { checksVoidReturn: false }],
      '@typescript-eslint/no-misused-spread': ['warn'],
      '@typescript-eslint/no-mixed-enums': ['warn'],
      '@typescript-eslint/no-namespace': ['warn'],
      '@typescript-eslint/no-non-null-asserted-nullish-coalescing': ['warn'],
      '@typescript-eslint/no-non-null-asserted-optional-chain': ['warn'],
      '@typescript-eslint/no-non-null-assertion': ['warn'],
      '@typescript-eslint/no-redundant-type-constituents': ['warn'],
      '@typescript-eslint/no-require-imports': ['warn'],
      '@typescript-eslint/no-restricted-imports': [
        'warn',
        {
          name: 'date-fns',
          importNames: [
            'getDate',
            'getDay',
            'getFullYear',
            'getHours',
            'getMilliseconds',
            'getMinutes',
            'getMonth',
            'getSeconds',
            'getTime',
            'getTimezoneOffset',
            'getUTCDate',
            'getUTCDay',
            'getUTCFullYear',
            'getUTCHours',
            'getUTCMilliseconds',
            'getUTCMinutes',
            'getUTCMonth',
            'getUTCSeconds',
            'getYear',
          ],
          message: 'these methods exist on the date object itself',
        },
        { name: 'date-fns-tz', message: 'use date-fns/tz (>=4.0.0)' },
        { name: 'execa', message: '? (still enter this!)' },
        {
          name: 'io-ts',
          importNames: ['exact', 'interface', 'intersection', 'partial', 'readonly', 'strict'],
          message: '? (still enter this!)',
        },
        { name: 'lodash-es', importNames: ['chain'], message: "lodash-es doesn't support 'chain'" },
        { name: 'lodash', message: "use 'lodash-es'" },
        { name: 'mongodb', importNames: ['ObjectId'], message: "use the import from 'bson'" },
        { name: 'node:fs', message: 'we should use our own customLib impplementation' },
        { name: 'node:fs/promises', message: 'we should use our own customLib impplementation' },
        { name: 'puppeteer', importNames: ['launch'], message: 'use the central browser or headlessBrowser' },
        {
          name: 'react-use',
          importNames: ['useAsync'],
          message: "useAsync swallows errors, so use the custom 'useAsyncEffect' from customLib 'react-custom' instead",
        },
      ],
      '@typescript-eslint/no-restricted-types': ['warn', { types: { object: "don't use it" } }],
      '@typescript-eslint/no-shadow': ['warn', { builtinGlobals: true, hoist: 'all' }],
      '@typescript-eslint/no-this-alias': ['warn'],
      '@typescript-eslint/no-unnecessary-boolean-literal-compare': ['warn'],
      '@typescript-eslint/no-unnecessary-condition': ['warn'],
      '@typescript-eslint/no-unnecessary-parameter-property-assignment': ['warn'],
      '@typescript-eslint/no-unnecessary-qualifier': ['warn'],
      '@typescript-eslint/no-unnecessary-template-expression': ['warn'],
      '@typescript-eslint/no-unnecessary-type-arguments': ['warn'],
      '@typescript-eslint/no-unnecessary-type-assertion': ['warn'],
      '@typescript-eslint/no-unnecessary-type-constraint': ['warn'],
      '@typescript-eslint/no-unnecessary-type-conversion': ['warn'],
      '@typescript-eslint/no-unsafe-argument': ['warn'],
      '@typescript-eslint/no-unsafe-declaration-merging': ['warn'],
      '@typescript-eslint/no-unsafe-enum-comparison': ['warn'],
      '@typescript-eslint/no-unsafe-function-type': ['warn'],
      '@typescript-eslint/no-unsafe-type-assertion': ['warn'],
      '@typescript-eslint/no-unsafe-unary-minus': ['warn'],
      '@typescript-eslint/no-unused-expressions': ['warn', { enforceForJSX: true }],
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      '@typescript-eslint/no-useless-constructor': ['warn'],
      '@typescript-eslint/no-useless-empty-export': ['warn'],
      '@typescript-eslint/no-var-requires': ['warn'],
      '@typescript-eslint/no-wrapper-object-types': ['warn'],
      '@typescript-eslint/non-nullable-type-assertion-style': ['warn'],
      '@typescript-eslint/only-throw-error': ['warn'],
      '@typescript-eslint/parameter-properties': [
        'warn',
        { allow: ['private readonly', 'protected readonly', 'public readonly'] },
      ],
      '@typescript-eslint/prefer-as-const': ['warn'],
      '@typescript-eslint/prefer-destructuring': ['warn'],
      '@typescript-eslint/prefer-enum-initializers': ['warn'],
      '@typescript-eslint/prefer-find': ['warn'],
      '@typescript-eslint/prefer-for-of': ['warn'],
      '@typescript-eslint/prefer-function-type': ['warn'],
      '@typescript-eslint/prefer-includes': ['warn'],
      '@typescript-eslint/prefer-literal-enum-member': ['warn'],
      '@typescript-eslint/prefer-namespace-keyword': ['warn'],
      '@typescript-eslint/prefer-nullish-coalescing': ['warn'],
      '@typescript-eslint/prefer-optional-chain': ['warn'],
      '@typescript-eslint/prefer-promise-reject-errors': ['warn'],
      '@typescript-eslint/prefer-readonly': ['warn'],
      '@typescript-eslint/prefer-reduce-type-parameter': ['warn'],
      '@typescript-eslint/prefer-return-this-type': ['warn'],
      '@typescript-eslint/prefer-string-starts-ends-with': ['warn'],
      '@typescript-eslint/prefer-ts-expect-error': ['warn'],
      '@typescript-eslint/promise-function-async': ['warn'],
      '@typescript-eslint/related-getter-setter-pairs': ['warn'],
      '@typescript-eslint/require-await': ['warn'],
      '@typescript-eslint/restrict-plus-operands': ['warn'],
      '@typescript-eslint/return-await': ['warn'],
      '@typescript-eslint/sort-type-constituents': ['warn'],
      '@typescript-eslint/strict-boolean-expressions': [
        'warn',
        { allowNullableObject: false, allowNumber: false, allowString: false },
      ],
      '@typescript-eslint/switch-exhaustiveness-check': ['warn'],
      '@typescript-eslint/triple-slash-reference': ['warn'],
      '@typescript-eslint/unbound-method': ['warn'],
      '@typescript-eslint/unified-signatures': ['warn'],
      '@typescript-eslint/use-unknown-in-catch-callback-variable': ['warn'],
      'accessor-pairs': ['warn'],
      'array-callback-return': ['warn'],
      'arrow-body-style': ['warn'],
      'block-scoped-var': ['warn'],
      'callback-return': ['warn'],
      'capitalized-comments': ['warn', 'never', { ignorePattern: 'NOTE: |TODO: ' }],
      'consistent-this': ['warn'],
      'constructor-super': ['warn'],
      'curly': ['warn', 'all'],
      'custom/always-call-log-errors-return-function': ['warn'],
      'custom/copy-filename': ['warn'],
      'custom/custom-types': ['warn'],
      'custom/forbid-breaking-out-of-custom-lib': ['warn'],
      'custom/force': ['warn'],
      'custom/get-actor-function-name': ['warn'],
      'custom/io-ts-only-array': ['warn'],
      'custom/io-ts-union-order': ['warn'],
      'custom/lodash-commit-value': ['warn'],
      'custom/no-delete': ['warn'],
      'custom/no-forbidden-string': [
        'warn',
        ['colour', 'gi'],
        ['transactionContainer\\d', 'gi'],
        ['cost.?center', 'gi'],
        ['exect', 'gi'],
        ['grey', 'gi'],
        ['ileName', 'g'],
        ['track.?area', 'gi'],
        ['preperation', 'gi'],
        ['focusses', 'gi'],
        ['dependanc', 'gi'],
      ],
      'custom/no-newline-between-imports': ['warn'],
      'custom/no-object-id-simple-compare': ['warn'],
      'custom/no-single-element-array-concat': ['warn'],
      'custom/no-single-line-disable-block': ['warn'],
      'custom/no-useless-lodash-chain': ['warn'],
      'custom/no-useless-string-template': ['warn'],
      'custom/project-frontend-apps-use-document-title': ['warn'],
      'custom/proper-sub-folder-structure': ['warn'],
      'custom/redux': ['warn'],
      'custom/redux-use-selector-name': ['warn'],
      'custom/require-array-element': ['warn'],
      'custom/require-google-authorization-wrapper': ['warn'],
      'custom/require-matching-id-names': [
        'warn',
        {
          entityId: 'oldEntityId',
          oNodeId: 'repeatSourceONodeId',
          parentONodeId: 'oNodeId',
          replaceWorkdayId: 'workdayId',
          rootONodeId: 'oNodeId',
        },
      ],
      'custom/reselect': ['warn'],
      'custom/single-letter-argument': ['warn'],
      'custom/sort-disable-rules': ['warn'],
      'custom/ts-extension': ['warn'],
      'custom/validate-destructured-object-parameter': ['warn'],
      'custom/validate-import-path': ['warn'],
      'custom/validate-io-ts-schema': ['warn'],
      'default-case-last': ['warn'],
      'eqeqeq': ['warn'],
      'for-direction': ['warn'],
      'func-name-matching': ['warn'],
      'func-names': ['warn'],
      'func-style': ['warn'],
      'functional/prefer-property-signatures': ['warn'],
      'functional/prefer-readonly-type': ['warn', { ignoreCollections: true }],
      'functional/prefer-tacit': ['warn'],
      'functional/readonly-type': ['warn', 'keyword'],
      'getter-return': ['warn'],
      'grouped-accessor-pairs': ['warn'],
      'handle-callback-err': ['warn'],
      'id-blacklist': ['warn'],
      'id-denylist': ['warn'],
      'id-match': ['warn'],
      'import/consistent-type-specifier-style': ['warn'],
      'import/default': ['warn'],
      'import/enforce-node-protocol-usage': ['warn', 'always'],
      'import/export': ['warn'],
      'import/extensions': ['warn', { js: 'ignorePackages', jsx: 'always', json: 'always', style: 'always' }],
      'import/first': ['warn'],
      'import/imports-first': ['warn'],
      'import/namespace': ['warn'],
      'import/newline-after-import': ['warn'],
      'import/no-absolute-path': ['warn'],
      'import/no-amd': ['warn'],
      'import/no-anonymous-default-export': ['warn'],
      'import/no-commonjs': ['warn'],
      'import/no-cycle': ['warn'],
      'import/no-default-export': ['warn'],
      'import/no-duplicates': ['warn'],
      'import/no-dynamic-require': ['warn'],
      'import/no-empty-named-blocks': ['warn'],
      'import/no-extraneous-dependencies': ['warn'],
      'import/no-mutable-exports': ['warn'],
      'import/no-named-as-default': ['warn'],
      'import/no-named-as-default-member': ['warn'],
      'import/no-named-default': ['warn'],
      'import/no-namespace': ['warn'],
      'import/no-restricted-paths': ['warn'],
      'import/no-self-import': ['warn'],
      'import/no-unassigned-import': ['warn'],
      'import/no-unused-modules': ['warn'],
      'import/no-useless-path-segments': ['warn'],
      'import/no-webpack-loader-syntax': ['warn'],
      'import/order': [
        'warn',
        { alphabetize: { order: 'asc', orderImportKind: 'asc', caseInsensitive: true }, warnOnUnassignedImports: true },
      ],
      'lodash/callback-binding': ['warn'],
      'lodash/chain-style': ['warn'],
      'lodash/collection-ordering': ['warn'],
      'lodash/collection-return': ['warn'],
      'lodash/consistent-compose': ['warn'],
      'lodash/identity-shorthand': ['warn'],
      'lodash/matches-prop-shorthand': ['warn', 'never'],
      'lodash/matches-shorthand': ['warn', 'never'],
      'lodash/no-double-unwrap': ['warn'],
      'lodash/no-extra-args': ['warn'],
      'lodash/no-unbound-this': ['warn'],
      'lodash/path-style': ['warn'],
      'lodash/prefer-compact': ['warn'],
      'lodash/prefer-filter': ['warn'],
      'lodash/prefer-find': ['warn'],
      'lodash/prefer-flat-map': ['warn'],
      'lodash/prefer-get': ['warn'],
      'lodash/prefer-immutable-method': ['warn'],
      'lodash/prefer-includes': ['warn'],
      'lodash/prefer-is-nil': ['warn'],
      'lodash/prefer-lodash-chain': ['warn'],
      'lodash/prefer-lodash-typecheck': ['warn'],
      'lodash/prefer-over-quantifier': ['warn'],
      'lodash/prefer-reject': ['warn'],
      'lodash/prefer-some': ['warn'],
      'lodash/prefer-startswith': ['warn'],
      'lodash/prefer-times': ['warn'],
      'lodash/prefer-wrapper-method': ['warn'],
      'lodash/preferred-alias': ['warn'],
      'lodash/prop-shorthand': ['warn', 'never'],
      'lodash/unwrap': ['warn'],
      'logical-assignment-operators': ['warn', 'always', { enforceForIfStatements: true }],
      'max-nested-callbacks': ['warn'],
      'n/exports-style': ['warn'],
      'n/global-require': ['warn'],
      'n/hashbang': ['warn'],
      'n/no-callback-literal': ['warn'],
      'n/no-deprecated-api': ['warn'],
      'n/no-exports-assign': ['warn'],
      'n/no-extraneous-require': ['warn'],
      'n/no-missing-require': ['warn'],
      'n/no-restricted-require': ['warn'],
      'n/no-unpublished-bin': ['warn'],
      'n/no-unpublished-require': ['warn'],
      'n/no-unsupported-features/es-builtins': ['warn', { version: '>=24.5.0' }],
      'n/no-unsupported-features/es-syntax': ['warn', { version: '>=24.5.0' }],
      'n/no-unsupported-features/node-builtins': [
        'warn',
        {
          ignores: ['crypto', 'fetch', 'localStorage', 'navigator.userAgent', 'navigator', 'WebSocket'],
          version: '>=24.5.0',
        },
      ],
      'n/prefer-global/buffer': ['warn'],
      'n/prefer-global/console': ['warn'],
      'n/prefer-global/process': ['warn'],
      'n/prefer-global/text-decoder': ['warn'],
      'n/prefer-global/text-encoder': ['warn'],
      'n/prefer-global/url': ['warn'],
      'n/prefer-global/url-search-params': ['warn'],
      'n/prefer-promises/dns': ['warn'],
      'n/prefer-promises/fs': ['warn'],
      'n/process-exit-as-throw': ['warn'],
      'n/shebang': ['warn'],
      'new-cap': ['warn'],
      'no-alert': ['warn'],
      'no-bitwise': ['warn'],
      'no-buffer-constructor': ['warn'],
      'no-caller': ['warn'],
      'no-case-declarations': ['warn'],
      'no-class-assign': ['warn'],
      'no-compare-neg-zero': ['warn'],
      'no-cond-assign': ['warn', 'always'],
      'no-console': ['warn', { allow: ['error', 'warn'] }],
      'no-const-assign': ['warn'],
      'no-constant-binary-expression': ['warn'],
      'no-constant-condition': ['warn'],
      'no-constructor-return': ['warn'],
      'no-control-regex': ['warn'],
      'no-debugger': ['warn'],
      'no-delete-var': ['warn'],
      'no-div-regex': ['warn'],
      'no-dupe-args': ['warn'],
      'no-dupe-else-if': ['warn'],
      'no-dupe-keys': ['warn'],
      'no-duplicate-case': ['warn'],
      'no-else-return': ['warn'],
      'no-empty': ['warn', { allowEmptyCatch: true }],
      'no-empty-pattern': ['warn'],
      'no-empty-static-block': ['warn'],
      'no-eq-null': ['warn'],
      'no-eval': ['warn'],
      'no-ex-assign': ['warn'],
      'no-extend-native': ['warn'],
      'no-extra-bind': ['warn'],
      'no-extra-boolean-cast': ['warn'],
      'no-extra-label': ['warn'],
      'no-fallthrough': ['warn'],
      'no-func-assign': ['warn'],
      'no-global-assign': ['warn'],
      'no-implicit-coercion': ['warn'],
      'no-implicit-globals': ['warn'],
      'no-import-assign': ['warn'],
      'no-inner-declarations': ['warn'],
      'no-irregular-whitespace': ['warn'],
      'no-iterator': ['warn'],
      'no-label-var': ['warn'],
      'no-labels': ['warn'],
      'no-lone-blocks': ['warn'],
      'no-misleading-character-class': ['warn'],
      'no-mixed-requires': ['warn'],
      'no-multi-assign': ['warn'],
      'no-multi-str': ['warn'],
      'no-new': ['warn'],
      'no-new-func': ['warn'],
      'no-new-native-nonconstructor': ['warn'],
      'no-new-object': ['warn'],
      'no-new-require': ['warn'],
      'no-new-symbol': ['warn'],
      'no-new-wrappers': ['warn'],
      'no-nonoctal-decimal-escape': ['warn'],
      'no-obj-calls': ['warn'],
      'no-object-constructor': ['warn'],
      'no-octal-escape': ['warn'],
      'no-param-reassign': ['warn'],
      'no-path-concat': ['warn'],
      'no-plusplus': ['warn'],
      'no-promise-executor-return': ['warn'],
      'no-proto': ['warn'],
      'no-prototype-builtins': ['warn'],
      'no-regex-spaces': ['warn'],
      'no-restricted-exports': ['warn'],
      'no-restricted-globals': ['warn', 'fetch'],
      'no-restricted-modules': ['warn'],
      'no-restricted-properties': ['warn'],
      'no-restricted-syntax': ['warn', "Identifier[name='__dirname']", "Identifier[name='substr']"],
      'no-return-assign': ['warn'],
      'no-return-await': ['warn'],
      'no-script-url': ['warn'],
      'no-self-assign': ['warn'],
      'no-self-compare': ['warn'],
      'no-sequences': ['warn'],
      'no-setter-return': ['warn'],
      'no-shadow-restricted-names': ['warn'],
      'no-sparse-arrays': ['warn'],
      'no-template-curly-in-string': ['warn'],
      'no-this-before-super': ['warn'],
      'no-unassigned-vars': ['warn'],
      'no-undef': ['warn'],
      'no-undef-init': ['warn'],
      'no-unexpected-multiline': ['warn'],
      'no-unmodified-loop-condition': ['warn'],
      'no-unneeded-ternary': ['warn'],
      'no-unreachable': ['warn'],
      'no-unreachable-loop': ['warn'],
      'no-unsafe-finally': ['warn'],
      'no-unsafe-negation': ['warn'],
      'no-unsafe-optional-chaining': ['warn'],
      'no-unused-labels': ['warn'],
      'no-unused-private-class-members': ['warn'],
      'no-useless-assignment': ['warn'],
      'no-useless-call': ['warn'],
      'no-useless-catch': ['warn'],
      'no-useless-computed-key': ['warn'],
      'no-useless-concat': ['warn'],
      'no-useless-rename': ['warn'],
      'no-useless-return': ['warn'],
      'no-var': ['warn'],
      'no-void': ['warn'],
      'no-with': ['warn'],
      'object-shorthand': ['warn'],
      'one-var': ['warn', 'never'],
      'operator-assignment': ['warn'],
      'prefer-arrow-callback': ['warn'],
      'prefer-const': ['warn'],
      'prefer-exponentiation-operator': ['warn'],
      'prefer-numeric-literals': ['warn'],
      'prefer-object-has-own': ['warn'],
      'prefer-object-spread': ['warn'],
      'prefer-regex-literals': ['warn'],
      'prefer-rest-params': ['warn'],
      'prefer-spread': ['warn'],
      'prefer-template': ['warn'],
      'promise/always-return': ['warn'],
      'promise/catch-or-return': ['warn'],
      'promise/no-callback-in-promise': ['warn'],
      'promise/no-multiple-resolved': ['warn'],
      'promise/no-nesting': ['warn'],
      'promise/no-new-statics': ['warn'],
      'promise/no-promise-in-callback': ['warn'],
      'promise/no-return-in-finally': ['warn'],
      'promise/no-return-wrap': ['warn'],
      'promise/param-names': ['warn'],
      'promise/prefer-await-to-callbacks': ['warn'],
      'promise/prefer-await-to-then': ['warn'],
      'promise/prefer-catch': ['warn'],
      'promise/spec-only': ['warn'],
      'promise/valid-params': ['warn'],
      'radix': ['warn'],
      'regexp/confusing-quantifier': ['warn'],
      'regexp/control-character-escape': ['warn'],
      'regexp/grapheme-string-literal': ['warn'],
      'regexp/hexadecimal-escape': ['warn'],
      'regexp/letter-case': ['warn'],
      'regexp/match-any': ['warn'],
      'regexp/negation': ['warn'],
      'regexp/no-contradiction-with-assertion': ['warn'],
      'regexp/no-control-character': ['warn'],
      'regexp/no-dupe-characters-character-class': ['warn'],
      'regexp/no-dupe-disjunctions': ['warn'],
      'regexp/no-empty-alternative': ['warn'],
      'regexp/no-empty-capturing-group': ['warn'],
      'regexp/no-empty-character-class': ['warn'],
      'regexp/no-empty-group': ['warn'],
      'regexp/no-empty-lookarounds-assertion': ['warn'],
      'regexp/no-empty-string-literal': ['warn'],
      'regexp/no-escape-backspace': ['warn'],
      'regexp/no-extra-lookaround-assertions': ['warn'],
      'regexp/no-invalid-regexp': ['warn'],
      'regexp/no-invisible-character': ['warn'],
      'regexp/no-lazy-ends': ['warn'],
      'regexp/no-legacy-features': ['warn'],
      'regexp/no-misleading-capturing-group': ['warn'],
      'regexp/no-misleading-unicode-character': ['warn'],
      'regexp/no-missing-g-flag': ['warn'],
      'regexp/no-non-standard-flag': ['warn'],
      'regexp/no-obscure-range': ['warn'],
      'regexp/no-octal': ['warn'],
      'regexp/no-optional-assertion': ['warn'],
      'regexp/no-potentially-useless-backreference': ['warn'],
      'regexp/no-standalone-backslash': ['warn'],
      'regexp/no-trivially-nested-assertion': ['warn'],
      'regexp/no-trivially-nested-quantifier': ['warn'],
      'regexp/no-unused-capturing-group': ['warn'],
      'regexp/no-useless-assertions': ['warn'],
      'regexp/no-useless-backreference': ['warn'],
      'regexp/no-useless-character-class': ['warn'],
      'regexp/no-useless-dollar-replacements': ['warn'],
      'regexp/no-useless-escape': ['warn'],
      'regexp/no-useless-flag': ['warn'],
      'regexp/no-useless-lazy': ['warn'],
      'regexp/no-useless-non-capturing-group': ['warn'],
      'regexp/no-useless-quantifier': ['warn'],
      'regexp/no-useless-range': ['warn'],
      'regexp/no-useless-set-operand': ['warn'],
      'regexp/no-useless-string-literal': ['warn'],
      'regexp/no-useless-two-nums-quantifier': ['warn'],
      'regexp/no-zero-quantifier': ['warn'],
      'regexp/optimal-lookaround-quantifier': ['warn'],
      'regexp/optimal-quantifier-concatenation': ['warn'],
      'regexp/prefer-character-class': ['warn'],
      'regexp/prefer-d': ['warn'],
      'regexp/prefer-escape-replacement-dollar-char': ['warn'],
      'regexp/prefer-lookaround': ['warn'],
      'regexp/prefer-named-backreference': ['warn'],
      'regexp/prefer-named-capture-group': ['warn'],
      'regexp/prefer-named-replacement': ['warn'],
      'regexp/prefer-plus-quantifier': ['warn'],
      'regexp/prefer-predefined-assertion': ['warn'],
      'regexp/prefer-quantifier': ['warn'],
      'regexp/prefer-question-quantifier': ['warn'],
      'regexp/prefer-range': ['warn'],
      'regexp/prefer-regexp-exec': ['warn'],
      'regexp/prefer-regexp-test': ['warn'],
      'regexp/prefer-result-array-groups': ['warn'],
      'regexp/prefer-set-operation': ['warn'],
      'regexp/prefer-star-quantifier': ['warn'],
      'regexp/prefer-unicode-codepoint-escapes': ['warn'],
      'regexp/prefer-w': ['warn'],
      'regexp/require-unicode-regexp': ['warn'],
      'regexp/require-unicode-sets-regexp': ['warn'],
      'regexp/simplify-set-operations': ['warn'],
      'regexp/sort-alternatives': ['warn'],
      'regexp/sort-character-class-elements': ['warn'],
      'regexp/sort-flags': ['warn'],
      'regexp/strict': ['warn'],
      'regexp/unicode-escape': ['warn'],
      'regexp/unicode-property': ['warn'],
      'regexp/use-ignore-case': ['warn'],
      'require-atomic-updates': ['warn'],
      'require-yield': ['warn'],
      'sonarjs/anchor-precedence': ['warn'],
      'sonarjs/argument-type': ['warn'],
      'sonarjs/arguments-order': ['warn'],
      'sonarjs/arguments-usage': ['warn'],
      'sonarjs/array-callback-without-return': ['warn'],
      'sonarjs/array-constructor': ['warn'],
      'sonarjs/arrow-function-convention': ['warn'],
      'sonarjs/assertions-in-tests': ['warn'],
      'sonarjs/aws-apigateway-public-api': ['warn'],
      'sonarjs/aws-ec2-rds-dms-public': ['warn'],
      'sonarjs/aws-ec2-unencrypted-ebs-volume': ['warn'],
      'sonarjs/aws-efs-unencrypted': ['warn'],
      'sonarjs/aws-iam-all-privileges': ['warn'],
      'sonarjs/aws-iam-all-resources-accessible': ['warn'],
      'sonarjs/aws-iam-privilege-escalation': ['warn'],
      'sonarjs/aws-iam-public-access': ['warn'],
      'sonarjs/aws-opensearchservice-domain': ['warn'],
      'sonarjs/aws-rds-unencrypted-databases': ['warn'],
      'sonarjs/aws-restricted-ip-admin-access': ['warn'],
      'sonarjs/aws-s3-bucket-granted-access': ['warn'],
      'sonarjs/aws-s3-bucket-insecure-http': ['warn'],
      'sonarjs/aws-s3-bucket-public-access': ['warn'],
      'sonarjs/aws-s3-bucket-server-encryption': ['warn'],
      'sonarjs/aws-s3-bucket-versioning': ['warn'],
      'sonarjs/aws-sagemaker-unencrypted-notebook': ['warn'],
      'sonarjs/aws-sns-unencrypted-topics': ['warn'],
      'sonarjs/aws-sqs-unencrypted-queue': ['warn'],
      'sonarjs/bitwise-operators': ['warn'],
      'sonarjs/bool-param-default': ['warn'],
      'sonarjs/call-argument-line': ['warn'],
      'sonarjs/certificate-transparency': ['warn'],
      'sonarjs/chai-determinate-assertion': ['warn'],
      'sonarjs/class-name': ['warn'],
      'sonarjs/class-prototype': ['warn'],
      'sonarjs/comma-or-logical-or-case': ['warn'],
      'sonarjs/comment-regex': ['warn'],
      'sonarjs/concise-regex': ['warn'],
      'sonarjs/conditional-indentation': ['warn'],
      'sonarjs/confidential-information-logging': ['warn'],
      'sonarjs/constructor-for-side-effects': ['warn'],
      'sonarjs/content-length': ['warn'],
      'sonarjs/content-security-policy': ['warn'],
      'sonarjs/cookie-no-httponly': ['warn'],
      'sonarjs/cors': ['warn'],
      'sonarjs/csrf': ['warn'],
      'sonarjs/destructuring-assignment-syntax': ['warn'],
      'sonarjs/disabled-auto-escaping': ['warn'],
      'sonarjs/disabled-resource-integrity': ['warn'],
      'sonarjs/disabled-timeout': ['warn'],
      'sonarjs/dns-prefetching': ['warn'],
      'sonarjs/duplicates-in-character-class': ['warn'],
      'sonarjs/empty-string-repetition': ['warn'],
      'sonarjs/existing-groups': ['warn'],
      'sonarjs/file-name-differ-from-class': ['warn'],
      'sonarjs/file-permissions': ['warn'],
      'sonarjs/file-uploads': ['warn'],
      'sonarjs/fixme-tag': ['warn'],
      'sonarjs/for-loop-increment-sign': ['warn'],
      'sonarjs/frame-ancestors': ['warn'],
      'sonarjs/function-inside-loop': ['warn'],
      'sonarjs/future-reserved-words': ['warn'],
      'sonarjs/generator-without-yield': ['warn'],
      'sonarjs/hashing': ['warn'],
      'sonarjs/hidden-files': ['warn'],
      'sonarjs/in-operator-type-error': ['warn'],
      'sonarjs/inconsistent-function-call': ['warn'],
      'sonarjs/index-of-compare-to-positive-number': ['warn'],
      'sonarjs/insecure-cookie': ['warn'],
      'sonarjs/insecure-jwt-token': ['warn'],
      'sonarjs/inverted-assertion-arguments': ['warn'],
      'sonarjs/label-position': ['warn'],
      'sonarjs/link-with-target-blank': ['warn'],
      'sonarjs/max-switch-cases': ['warn'],
      'sonarjs/misplaced-loop-counter': ['warn'],
      'sonarjs/new-operator-misuse': ['warn'],
      'sonarjs/no-all-duplicated-branches': ['warn'],
      'sonarjs/no-alphabetical-sort': ['warn'],
      'sonarjs/no-angular-bypass-sanitization': ['warn'],
      'sonarjs/no-associative-arrays': ['warn'],
      'sonarjs/no-async-constructor': ['warn'],
      'sonarjs/no-built-in-override': ['warn'],
      'sonarjs/no-case-label-in-switch': ['warn'],
      'sonarjs/no-code-after-done': ['warn'],
      'sonarjs/no-collection-size-mischeck': ['warn'],
      'sonarjs/no-duplicate-in-composite': ['warn'],
      'sonarjs/no-duplicated-branches': ['warn'],
      'sonarjs/no-element-overwrite': ['warn'],
      'sonarjs/no-empty-after-reluctant': ['warn'],
      'sonarjs/no-empty-alternatives': ['warn'],
      'sonarjs/no-empty-collection': ['warn'],
      'sonarjs/no-empty-test-file': ['warn'],
      'sonarjs/no-equals-in-for-termination': ['warn'],
      'sonarjs/no-exclusive-tests': ['warn'],
      'sonarjs/no-extra-arguments': ['warn'],
      'sonarjs/no-for-in-iterable': ['warn'],
      'sonarjs/no-function-declaration-in-block': ['warn'],
      'sonarjs/no-global-this': ['warn'],
      'sonarjs/no-globals-shadowing': ['warn'],
      'sonarjs/no-gratuitous-expressions': ['warn'],
      'sonarjs/no-hardcoded-passwords': ['warn'],
      'sonarjs/no-hardcoded-secrets': ['warn'],
      'sonarjs/no-hook-setter-in-body': ['warn'],
      'sonarjs/no-identical-conditions': ['warn'],
      'sonarjs/no-identical-expressions': ['warn'],
      'sonarjs/no-identical-functions': ['warn'],
      'sonarjs/no-ignored-exceptions': ['warn'],
      'sonarjs/no-ignored-return': ['warn'],
      'sonarjs/no-implicit-dependencies': ['warn'],
      'sonarjs/no-implicit-global': ['warn'],
      'sonarjs/no-in-misuse': ['warn'],
      'sonarjs/no-incomplete-assertions': ['warn'],
      'sonarjs/no-incorrect-string-concat': ['warn'],
      'sonarjs/no-intrusive-permissions': ['warn'],
      'sonarjs/no-inverted-boolean-check': ['warn'],
      'sonarjs/no-ip-forward': ['warn'],
      'sonarjs/no-literal-call': ['warn'],
      'sonarjs/no-mime-sniff': ['warn'],
      'sonarjs/no-misleading-array-reverse': ['warn'],
      'sonarjs/no-mixed-content': ['warn'],
      'sonarjs/no-nested-assignment': ['warn'],
      'sonarjs/no-nested-incdec': ['warn'],
      'sonarjs/no-nested-switch': ['warn'],
      'sonarjs/no-one-iteration-loop': ['warn'],
      'sonarjs/no-os-command-from-path': ['warn'],
      'sonarjs/no-parameter-reassignment': ['warn'],
      'sonarjs/no-primitive-wrappers': ['warn'],
      'sonarjs/no-redundant-assignments': ['warn'],
      'sonarjs/no-redundant-boolean': ['warn'],
      'sonarjs/no-redundant-jump': ['warn'],
      'sonarjs/no-redundant-optional': ['warn'],
      'sonarjs/no-redundant-parentheses': ['warn'],
      'sonarjs/no-referrer-policy': ['warn'],
      'sonarjs/no-require-or-define': ['warn'],
      'sonarjs/no-return-type-any': ['warn'],
      'sonarjs/no-same-argument-assert': ['warn'],
      'sonarjs/no-same-line-conditional': ['warn'],
      'sonarjs/no-skipped-tests': ['warn'],
      'sonarjs/no-small-switch': ['warn'],
      'sonarjs/no-sonar-comments': ['warn'],
      'sonarjs/no-tab': ['warn'],
      'sonarjs/no-table-as-layout': ['warn'],
      'sonarjs/no-try-promise': ['warn'],
      'sonarjs/no-undefined-argument': ['warn'],
      'sonarjs/no-unenclosed-multiline-block': ['warn'],
      'sonarjs/no-uniq-key': ['warn'],
      'sonarjs/no-unsafe-unzip': ['warn'],
      'sonarjs/no-unthrown-error': ['warn'],
      'sonarjs/no-unused-collection': ['warn'],
      'sonarjs/no-unused-function-argument': ['warn'],
      'sonarjs/no-use-of-empty-return-value': ['warn'],
      'sonarjs/no-useless-increment': ['warn'],
      'sonarjs/no-useless-intersection': ['warn'],
      'sonarjs/no-useless-react-setstate': ['warn'],
      'sonarjs/no-variable-usage-before-declaration': ['warn'],
      'sonarjs/no-vue-bypass-sanitization': ['warn'],
      'sonarjs/no-weak-cipher': ['warn'],
      'sonarjs/no-weak-keys': ['warn'],
      'sonarjs/non-existent-operator': ['warn'],
      'sonarjs/non-number-in-arithmetic-expression': ['warn'],
      'sonarjs/null-dereference': ['warn'],
      'sonarjs/object-alt-content': ['warn'],
      'sonarjs/operation-returning-nan': ['warn'],
      'sonarjs/os-command': ['warn'],
      'sonarjs/post-message': ['warn'],
      'sonarjs/prefer-default-last': ['warn'],
      'sonarjs/prefer-immediate-return': ['warn'],
      'sonarjs/prefer-object-literal': ['warn'],
      'sonarjs/prefer-promise-shorthand': ['warn'],
      'sonarjs/prefer-type-guard': ['warn'],
      'sonarjs/prefer-while': ['warn'],
      'sonarjs/production-debug': ['warn'],
      'sonarjs/public-static-readonly': ['warn'],
      'sonarjs/reduce-initial-value': ['warn'],
      'sonarjs/session-regeneration': ['warn'],
      'sonarjs/single-char-in-character-classes': ['warn'],
      'sonarjs/sockets': ['warn'],
      'sonarjs/sql-queries': ['warn'],
      'sonarjs/stable-tests': ['warn'],
      'sonarjs/standard-input': ['warn'],
      'sonarjs/stateful-regex': ['warn'],
      'sonarjs/strict-transport-security': ['warn'],
      'sonarjs/super-invocation': ['warn'],
      'sonarjs/table-header': ['warn'],
      'sonarjs/table-header-reference': ['warn'],
      'sonarjs/test-check-exception': ['warn'],
      'sonarjs/unicode-aware-regex': ['warn'],
      'sonarjs/unused-import': ['warn'],
      'sonarjs/unused-named-groups': ['warn'],
      'sonarjs/unverified-certificate': ['warn'],
      'sonarjs/unverified-hostname': ['warn'],
      'sonarjs/updated-const-var': ['warn'],
      'sonarjs/updated-loop-counter': ['warn'],
      'sonarjs/use-type-alias': ['warn'],
      'sonarjs/useless-string-operation': ['warn'],
      'sonarjs/values-not-convertible-to-numbers': ['warn'],
      'sonarjs/void-use': ['warn'],
      'sonarjs/weak-ssl': ['warn'],
      'sonarjs/web-sql-database': ['warn'],
      'sonarjs/x-powered-by': ['warn'],
      'sonarjs/xml-parser-xxe': ['warn'],
      'sonarjs/xpath': ['warn'],
      'sort-destructure-keys/sort-destructure-keys': ['warn'],
      'sort-imports': ['warn', { ignoreDeclarationSort: true }],
      'sort-keys-fix/sort-keys-fix': ['warn', 'asc', { caseSensitive: false, natural: true }],
      'sort-vars': ['warn'],
      'strict': ['warn'],
      'symbol-description': ['warn'],
      'typescript-sort-keys/interface': ['warn', 'asc', { caseSensitive: false, natural: true }],
      'typescript-sort-keys/string-enum': ['warn', 'asc', { caseSensitive: false, natural: true }],
      'unicode-bom': ['warn'],
      'unicorn/better-regex': ['warn'],
      'unicorn/catch-error-name': ['warn'],
      'unicorn/consistent-assert': ['warn'],
      'unicorn/consistent-date-clone': ['warn'],
      'unicorn/consistent-destructuring': ['warn'],
      'unicorn/consistent-empty-array-spread': ['warn'],
      'unicorn/consistent-existence-index-check': ['warn'],
      'unicorn/consistent-function-scoping': ['warn'],
      'unicorn/custom-error-definition': ['warn'],
      'unicorn/error-message': ['warn'],
      'unicorn/escape-case': ['warn'],
      'unicorn/expiring-todo-comments': ['warn'],
      'unicorn/new-for-builtins': ['warn'],
      'unicorn/no-abusive-eslint-disable': ['warn'],
      'unicorn/no-accessor-recursion': ['warn'],
      'unicorn/no-array-method-this-argument': ['warn'],
      'unicorn/no-array-push-push': ['warn'],
      'unicorn/no-await-in-promise-methods': ['warn'],
      'unicorn/no-console-spaces': ['warn'],
      'unicorn/no-document-cookie': ['warn'],
      'unicorn/no-for-loop': ['warn'],
      'unicorn/no-hex-escape': ['warn'],
      'unicorn/no-instanceof-array': ['warn'],
      'unicorn/no-instanceof-builtins': ['warn'],
      'unicorn/no-invalid-fetch-options': ['warn'],
      'unicorn/no-invalid-remove-event-listener': ['warn'],
      'unicorn/no-length-as-slice-end': ['warn'],
      'unicorn/no-magic-array-flat-depth': ['warn'],
      'unicorn/no-negated-condition': ['warn'],
      'unicorn/no-negation-in-equality-check': ['warn'],
      'unicorn/no-new-array': ['warn'],
      'unicorn/no-new-buffer': ['warn'],
      'unicorn/no-object-as-default-parameter': ['warn'],
      'unicorn/no-single-promise-in-promise-methods': ['warn'],
      'unicorn/no-static-only-class': ['warn'],
      'unicorn/no-thenable': ['warn'],
      'unicorn/no-this-assignment': ['warn'],
      'unicorn/no-typeof-undefined': ['warn'],
      'unicorn/no-unnecessary-array-flat-depth': ['warn'],
      'unicorn/no-unnecessary-array-splice-count': ['warn'],
      'unicorn/no-unnecessary-await': ['warn'],
      'unicorn/no-unnecessary-polyfills': ['warn'],
      'unicorn/no-unnecessary-slice-end': ['warn'],
      'unicorn/no-unreadable-array-destructuring': ['warn'],
      'unicorn/no-unreadable-iife': ['warn'],
      'unicorn/no-unused-properties': ['warn'],
      'unicorn/no-useless-error-capture-stack-trace': ['warn'],
      'unicorn/no-useless-fallback-in-spread': ['warn'],
      'unicorn/no-useless-length-check': ['warn'],
      'unicorn/no-useless-promise-resolve-reject': ['warn'],
      'unicorn/no-useless-spread': ['warn'],
      'unicorn/no-useless-switch-case': ['warn'],
      'unicorn/no-zero-fractions': ['warn'],
      'unicorn/number-literal-case': ['warn'],
      'unicorn/prefer-add-event-listener': ['warn'],
      'unicorn/prefer-array-find': ['warn'],
      'unicorn/prefer-array-flat-map': ['warn'],
      'unicorn/prefer-array-index-of': ['warn'],
      'unicorn/prefer-array-some': ['warn'],
      'unicorn/prefer-at': ['warn'],
      'unicorn/prefer-blob-reading-methods': ['warn'],
      'unicorn/prefer-class-fields': ['warn'],
      'unicorn/prefer-code-point': ['warn'],
      'unicorn/prefer-date-now': ['warn'],
      'unicorn/prefer-default-parameters': ['warn'],
      'unicorn/prefer-dom-node-append': ['warn'],
      'unicorn/prefer-dom-node-dataset': ['warn'],
      'unicorn/prefer-dom-node-remove': ['warn'],
      'unicorn/prefer-dom-node-text-content': ['warn'],
      'unicorn/prefer-event-target': ['warn'],
      'unicorn/prefer-export-from': ['warn'],
      'unicorn/prefer-global-this': ['warn'],
      'unicorn/prefer-import-meta-properties': ['warn'],
      'unicorn/prefer-includes': ['warn'],
      'unicorn/prefer-json-parse-buffer': ['warn'],
      'unicorn/prefer-keyboard-event-key': ['warn'],
      'unicorn/prefer-logical-operator-over-ternary': ['warn'],
      'unicorn/prefer-math-min-max': ['warn'],
      'unicorn/prefer-math-trunc': ['warn'],
      'unicorn/prefer-modern-dom-apis': ['warn'],
      'unicorn/prefer-modern-math-apis': ['warn'],
      'unicorn/prefer-native-coercion-functions': ['warn'],
      'unicorn/prefer-object-from-entries': ['warn'],
      'unicorn/prefer-query-selector': ['warn'],
      'unicorn/prefer-reflect-apply': ['warn'],
      'unicorn/prefer-set-has': ['warn'],
      'unicorn/prefer-set-size': ['warn'],
      'unicorn/prefer-single-call': ['warn'],
      'unicorn/prefer-string-raw': ['warn'],
      'unicorn/prefer-string-starts-ends-with': ['warn'],
      'unicorn/prefer-string-trim-start-end': ['warn'],
      'unicorn/prefer-structured-clone': ['warn'],
      'unicorn/prefer-top-level-await': ['warn'],
      'unicorn/prefer-type-error': ['warn'],
      'unicorn/relative-url-style': ['warn'],
      'unicorn/require-array-join-separator': ['warn'],
      'unicorn/require-module-specifiers': ['warn'],
      'unicorn/require-number-to-fixed-digits-argument': ['warn'],
      'unicorn/require-post-message-target-origin': ['warn'],
      'unicorn/string-content': ['warn'],
      'unicorn/switch-case-braces': ['warn'],
      'unicorn/template-indent': ['warn'],
      'unicorn/text-encoding-identifier-case': ['warn'],
      'unicorn/throw-new-error': ['warn'],
      'use-isnan': ['warn', { enforceForIndexOf: true }],
      'valid-typeof': ['warn'],
      'vars-on-top': ['warn'],
      'yoda': ['warn'],
      'you-dont-need-lodash-underscore/all': ['warn'],
      'you-dont-need-lodash-underscore/any': ['warn'],
      'you-dont-need-lodash-underscore/assign': ['warn'],
      'you-dont-need-lodash-underscore/bind': ['warn'],
      'you-dont-need-lodash-underscore/cast-array': ['warn'],
      'you-dont-need-lodash-underscore/clone-deep': ['warn'],
      'you-dont-need-lodash-underscore/collect': ['warn'],
      'you-dont-need-lodash-underscore/concat': ['warn'],
      'you-dont-need-lodash-underscore/contains': ['warn'],
      'you-dont-need-lodash-underscore/defaults': ['warn'],
      'you-dont-need-lodash-underscore/detect': ['warn'],
      'you-dont-need-lodash-underscore/each': ['warn'],
      'you-dont-need-lodash-underscore/ends-with': ['warn'],
      'you-dont-need-lodash-underscore/entries': ['warn'],
      'you-dont-need-lodash-underscore/every': ['warn'],
      'you-dont-need-lodash-underscore/extend-own': ['warn'],
      'you-dont-need-lodash-underscore/fill': ['warn'],
      'you-dont-need-lodash-underscore/filter': ['warn'],
      'you-dont-need-lodash-underscore/find': ['warn'],
      'you-dont-need-lodash-underscore/find-index': ['warn'],
      'you-dont-need-lodash-underscore/first': ['warn'],
      'you-dont-need-lodash-underscore/foldl': ['warn'],
      'you-dont-need-lodash-underscore/foldr': ['warn'],
      'you-dont-need-lodash-underscore/for-each': ['warn'],
      'you-dont-need-lodash-underscore/get': ['warn'],
      'you-dont-need-lodash-underscore/includes': ['warn'],
      'you-dont-need-lodash-underscore/index-of': ['warn'],
      'you-dont-need-lodash-underscore/inject': ['warn'],
      'you-dont-need-lodash-underscore/is-array': ['warn'],
      'you-dont-need-lodash-underscore/is-array-buffer': ['warn'],
      'you-dont-need-lodash-underscore/is-finite': ['warn'],
      'you-dont-need-lodash-underscore/is-integer': ['warn'],
      'you-dont-need-lodash-underscore/is-nan': ['warn'],
      'you-dont-need-lodash-underscore/is-null': ['warn'],
      'you-dont-need-lodash-underscore/is-undefined': ['warn'],
      'you-dont-need-lodash-underscore/join': ['warn'],
      'you-dont-need-lodash-underscore/keys': ['warn'],
      'you-dont-need-lodash-underscore/last-index-of': ['warn'],
      'you-dont-need-lodash-underscore/map': ['warn'],
      'you-dont-need-lodash-underscore/pad-end': ['warn'],
      'you-dont-need-lodash-underscore/pad-start': ['warn'],
      'you-dont-need-lodash-underscore/pairs': ['warn'],
      'you-dont-need-lodash-underscore/reduce': ['warn'],
      'you-dont-need-lodash-underscore/reduce-right': ['warn'],
      'you-dont-need-lodash-underscore/repeat': ['warn'],
      'you-dont-need-lodash-underscore/replace': ['warn'],
      'you-dont-need-lodash-underscore/reverse': ['warn'],
      'you-dont-need-lodash-underscore/select': ['warn'],
      'you-dont-need-lodash-underscore/slice': ['warn'],
      'you-dont-need-lodash-underscore/some': ['warn'],
      'you-dont-need-lodash-underscore/split': ['warn'],
      'you-dont-need-lodash-underscore/starts-with': ['warn'],
      'you-dont-need-lodash-underscore/to-lower': ['warn'],
      'you-dont-need-lodash-underscore/to-pairs': ['warn'],
      'you-dont-need-lodash-underscore/to-upper': ['warn'],
      'you-dont-need-lodash-underscore/trim': ['warn'],
      'you-dont-need-lodash-underscore/union-by': ['warn'],
      'you-dont-need-lodash-underscore/values': ['warn'],
    },
  },
  {
    files: ['@typesCustom/**/*.{js,jsx,ts,tsx,d.ts}'],
    rules: {
      'import/no-extraneous-dependencies': ['off'],
      'n/no-extraneous-import': ['off'],
      'sonarjs/no-implicit-dependencies': ['off'],
    },
  },
  {
    files: ['src/customLib/io-ts-custom/**/*.{js,jsx,ts,tsx,d.ts}'],
    rules: {
      '@typescript-eslint/no-restricted-imports': ['off'],
      'custom/validate-io-ts-schema': ['off'],
    },
  },
  {
    files: ['src/env/**/*.{js,jsx,ts,tsx,d.ts}'],
    rules: {
      'sonarjs/no-hardcoded-passwords': ['off'],
    },
  },
]
